### ISSUE TITLE
How tu use?

### ISSUE THREAD

**Issue by zhouzl7** [DevonHess/uTorrent-WebUI#1]
I put all files in the UTORRENT directory, but could not be used.

**Comment by DevonHess** [comment]
I made this a long time ago. (years before I uploaded it to GitHub)
If I remember correctly, you have to zip all the files into webui.zip and put that in your uTorrent appdata folder. [LINK](https://web.archive.org/web/20140513044652/http://www.utorrent.com/help/guides/webui)
This is specifically for uTorrent 2.2.1, and has a lot of changes and fixes. (none of which are documented, sorry)

If you're still using uTorrent, I would recommend switching to [qBittorrent](https://www.qbittorrent.org/), which also has a nice webui.
